version: "3.8"

services:
  php-backend:
    build: ./php-backend
    container_name: php-backend
    ports:
      - "8000:80"
    volumes:
      - ./php-backend:/var/www/html
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0  # or mysql:5.7 with platform fix
    platform: linux/x86_64
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: password
