version: '3'

services:
  frontend:
    build:
      context: ./react-frontend
    volumes:
      - ./react-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./node-backend
    volumes:
      - ./node-backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    working_dir: /app
    command: npx nodemon --legacy-watch server.js
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

